# Generated by Django 4.1 on 2023-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trello", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="project",
        ),
        migrations.AddField(
            model_name="task",
            name="projects",
            field=models.ManyToManyField(related_name="tasks", to="trello.project"),
        ),
    ]
